server:
  port: 8080

spring:
  application:
    name: UPLOAD-SERVICE
  datasource:
    url: jdbc:mariadb://localhost:3306/memberdb?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        format_sql: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /tmp/webmvc/temp
      max-file-size: 100MB
      max-request-size: 100MB

api:
  base:
    path: /api

upload:
  dir: /tmp/webmvc/upload